### ISSUE TITLE
Restore playlists after reset

### ISSUE THREAD

**Issue by falo2k** [emulamer/BeatOn#81]
**Is your feature request related to a problem? Please describe.**
Factory Reset seems to be the current goto of the Oculus Support team for any issue.  Unfortunately this means restoring SideQuest and BeatOn.  Despite restoring my Data folder and an app data backup from SideQuest, BeatOn has forgotten my playlists so all songs get imported directly into the single Custom playlist.

**Describe the solution you'd like**
It'd be great if it saved the playlist configuration to the data folder and could re-import this when scanning the songs folder.

**Comment by emulamer** [comment]
There's not UI for this, but there is some initial code in for supporting this through BS upgrades.  If you backed up the BeatOnData folder, try replacing the config.json file from the back up, then doing the "quick fix" in tools.  I'll leave it open because having a config import/export would be nice.

**Comment by falo2k** [comment]
Quick fix didn't seem to sort it unfortunately.  I've just gone through and rebuilt the playlists again.  Fingers crossed I've not no more resets coming up!

I don't think a UI is necessary, as long as there's a consistent manual way to ensure the playlists can remain / be recreatred.

**Comment by KarlDeux** [comment]
Good to know @falo2k ! I close this issue for now. Please, feel free to reopen it or make another one if needed.
